#!/bin/bash

source "$(dirname "$0")"/utils/utils.bash

# @brief: 格式化当前命令

safe source "$(dirname $0)"/var/poker_var.bash
safe source "$(dirname $0)"/format/format.bash

echo ${POKER_SUFFIX_CXX} | tr \; \\n | while read cxx_suffix; do
  Format . "-name "*.${cxx_suffix}"" ${POKER_FORMAT_FILE_PATH}
done

#for cxx_suffix in ${POKER_SUFFIX_CXX};do
#  echo cxx_suffix=${cxx_suffix}
#  Format . "-regex ".*\${cxx_suffix}"" ${POKER_FORMAT_FILE_PATH}
#done
#
#IFS=';' read -a words <<<"1;2;3;4;5"
#for word in "${words[@]}"
#do
#    echo "$word"
#done