#!/bin/bash

# @brief: 使用 terminator 启动配置文件中的多个任务，本脚本仅专注于解析配置中的参数
# @pos: 1 launch 配置文件位置
# @note: 由于 terminator -g option 无法正常使用，本脚本仅当不存在 terminator
#        进程时可顺利执行。
#        若已经有 terminator 运行，希望使用改脚本启动新的 terminator，可以手动
#        打开 terminator 的 preference 以加载新的 layout，然后执行
#                   terminator -l default
# @TODO: 解决 terminator -g 问题
# @TODO: 解决命令在终端排序不一致问题


# 引入 safe
source "$(dirname "$0")"/utils/utils.bash

# 引入 yaml 脚本解析
safe source "$(dirname "$0")"/parser/yaml/parse_yaml.sh
# 引入 terminator layout 处理
safe source "$(dirname "$0")"/terminator/launch.bash

# 执行目录：命令的列表，如 "/bin/:cd /bin/:mv"
DIR_COMMAND_LIST=()

# 检查配置文件存在性
if [ ! -e "$1" ];then
  echo "$1 doesn't not exist"
  exit 1
fi

# 解析配置文件，将根据配置文件生成相应变量
eval "$(parse_yaml "$1")"

# 遍历所有 task，读取每个 task 的配置项
# shellcheck disable=SC2154
for task_entry in ${task_};do
  # 任务名称
  name=${task_entry}_name
  # 工作目录
  work_directory=${task_entry}_directory
  # 执行命令
  command=${task_entry}_command

  DIR_COMMAND_LIST+=("${!name}:${!work_directory}:${!command}")
done

# 启动所有任务
launch "${DIR_COMMAND_LIST[@]}"



